-- Mantener las tablas de la versión 3.
-- Ejecuta la SQL que ya te entregué para:
-- mood_daily
-- mood_medications
-- mood_medication_logs
-- routine_items
-- mood_reminders
--
-- Esta versión v4 guarda localmente mientras no se configure una sesión
-- Supabase en el frontend. No elimina ni modifica tus datos existentes.
